### PR TITLE
Working on part 3

### PR DESCRIPTION
**Pull request by SChandarana**

### CODE REVIEW

**Review by FridaTveit — COMMENTED** [review]
I assume this is a work in progress? If so you can mark it as such https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request. That makes it more obvious to the reviewer that the changes aren't complete yet 🙂

**Comment by SChandarana** [comment]
image

**Review by FridaTveit — COMMENTED** [review]
Code looks good! A few comments on the screenshots:
- The alignment in the second table is different to the first, can you make them consistent?
- It would be useful to display the name of the stop
- It would be nice if the table headers were more distinguished from the table content, e.g. by the headers being bold

🙂

**Comment by SChandarana** [comment]
image

If postcode is invalid or no stops are found nearby
image

**Review by FridaTveit — APPROVED** [review]
Looks good! 🙂

**Pull request merged**
